# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "sqlite3", "~> 1.4"

gem "rspec", "~> 3.9"

gem "byebug", "~> 11.1"
